### ISSUE TITLE
permissions for chmod after recent updates

### ISSUE THREAD

**Issue by rainer-friederich** [edbizarro/bitbucket-pipelines-php7#3]
Running our gulp task with this image gives an error since your last commits:

```
[14:25:07] 'svg:min' errored after 3.59 s
[14:25:07] Error: EPERM: operation not permitted, chmod '/opt/atlassian/pipelines/agent/build/docroot/themes/wndrs/svg-src/icons/dist/arrow-down.svg'
[14:25:07] Error in plugin 'run-sequence(svg:min)'
Message:
    EPERM: operation not permitted, chmod '/opt/atlassian/pipelines/agent/build/docroot/themes/wndrs/svg-src/icons/dist/arrow-down.svg'
Details:
    errno: -1
    code: EPERM
    syscall: chmod
    path: /opt/atlassian/pipelines/agent/build/docroot/themes/wndrs/svg-src/icons/dist/arrow-down.svg
Stack:
Error: EPERM: operation not permitted, chmod '/opt/atlassian/pipelines/agent/build/docroot/themes/wndrs/svg-src/icons/dist/arrow-down.svg'
error Command failed with exit code 1.
```

I think because of commit f4491ea.
Any change to give the php user the rights to do this?

**Comment by edbizarro** [comment]
what command are u trying to run? maybe run with sudo?

**Comment by rainer-friederich** [comment]
I'm running the following:

```
- composer self-update --no-interaction
- composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader --no-dev
- yarn install
- yarn run gulp general
```

I run gulp through yarn because gulp is a project local npm dependency. This worked until a week ago. Now one gulp task (gulp svg-min) throws an error because it does a `chmod` on the cleaned svg's and the user running the command is not allowed to.

I would rather not run this commands via sudo but i'll try.

**Comment by rainer-friederich** [comment]
running it with sudo does not work:

```
- sudo yarn run gulp general
```

gives the following output:

`sudo: yarn: command not found`

**Comment by edbizarro** [comment]
I did a little research and found out that Bitbucket Pipelines now supports services (https://confluence.atlassian.com/bitbucket/test-with-databases-in-bitbucket-pipelines-856697462.html) 

so my image became obsolete.

You can use my base image (https://github.com/edbizarro/gitlab-ci-pipeline-php) and use the [services config](https://confluence.atlassian.com/bitbucket/test-with-databases-in-bitbucket-pipelines-856697462.html)
