### ISSUE TITLE
mysql root password

### ISSUE THREAD

**Issue by VinceG** [edbizarro/bitbucket-pipelines-php7#4]
Hey,

Thank you for creating this. It seems the mysql requires a password. using empty password or 'root' does not seem to work. am i missing anything?

Thanks again.

@edbizarro

**Comment by farizluqman** [comment]
up

**Comment by edbizarro** [comment]
I did a little research and found out that Bitbucket Pipelines now supports services (https://confluence.atlassian.com/bitbucket/test-with-databases-in-bitbucket-pipelines-856697462.html) 

so my image became obsolete.

You can use my base image (https://github.com/edbizarro/gitlab-ci-pipeline-php) and use the [services config](https://confluence.atlassian.com/bitbucket/test-with-databases-in-bitbucket-pipelines-856697462.html), which is the correct form for connect to the mysql
